// <auto-generated />

// Copyright (c) ThreeTrees. All rights reserved.
// Licensed under the BSD license. See LICENSE file in the project root for full license information.

using Microsoft.EntityFrameworkCore.Migrations;

namespace ThreeTrees.Metrics.DataAccess.Migrations
{
    /// <inheritdoc/>
    public partial class UpdateUniqueKeyForStatistic : Migration
    {
        /// <inheritdoc/>
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropIndex(
                name: "IX_EmployeeStatistics_Year_Month",
                table: "EmployeeStatistics");

            migrationBuilder.CreateIndex(
                name: "IX_EmployeeStatistics_Month_Year_EmployeeId",
                table: "EmployeeStatistics",
                columns: new[] { "Month", "Year", "EmployeeId" },
                unique: true);
        }

        /// <inheritdoc/>
        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropIndex(
                name: "IX_EmployeeStatistics_Month_Year_EmployeeId",
                table: "EmployeeStatistics");

            migrationBuilder.CreateIndex(
                name: "IX_EmployeeStatistics_Year_Month",
                table: "EmployeeStatistics",
                columns: new[] { "Year", "Month" },
                unique: true);
        }
    }
}
